dataset_path: parquet
dataset_kwargs:
  data_files:
    test: hf://datasets/aialliance/GEOBench-VLM/Single.parquet
process_docs: !function utils.geobench_single_filter_docs
task: geobench_single
test_split: test
output_type: generate_until
doc_to_visual: !function utils.geobench_doc_to_visual
doc_to_text: !function utils.geobench_single_doc_to_text
doc_to_target: !function utils.geobench_single_doc_to_target
generation_kwargs:
  max_new_tokens: 8
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.geobench_single_process_results
metric_list:
  - metric: single_accuracy
    aggregation: !function utils.geobench_single_aggregate
    higher_is_better: true
  - metric: per_task
    aggregation: !function utils.geobench_per_task_aggregate
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    post_prompt: "\nAnswer with the option letter only (A, B, C, D, or E)."
metadata:
  - version: 0.0
