group: google_fleurs 
task:
- fleurs_it_it
- fleurs_en_us
- fleurs_pt_br
- fleurs_de_de
- fleurs_th_th
- fleurs_fr_fr
- fleurs_es_419
- fleurs_vi_vn
- fleurs_ca_es
- google_fleurs_cmn_hans_cn
- fleurs_pl_pl
- fleurs_uk_ua
- fleurs_hi_in
- fleurs_it_it_val
- fleurs_en_us_val
- fleurs_pt_br_val
- fleurs_de_de_val
- fleurs_th_th_val
- fleurs_fr_fr_val
- fleurs_es_419_val
- fleurs_vi_vn_val
- fleurs_ca_es_val
- google_fleurs_cmn_hans_cn_val
- fleurs_pl_pl_val
- fleurs_uk_ua_val
- fleurs_hi_in_val
