include: textcaps_val.yaml
task: "textcaps_val_polos"
metric_list:
  - metric: textcaps_Bleu_4
    aggregation : !function utils.textcaps_bleu4
    higher_is_better : true
  - metric: textcaps_Bleu_3
    aggregation : !function utils.textcaps_bleu3
    higher_is_better : true
  - metric: textcaps_Bleu_2
    aggregation : !function utils.textcaps_bleu2
    higher_is_better : true
  - metric: textcaps_Bleu_1
    aggregation : !function utils.textcaps_bleu1
    higher_is_better : true
  - metric: textcaps_METEOR
    aggregation : !function utils.textcaps_meteor
    higher_is_better : true
  - metric: textcaps_ROUGE_L
    aggregation : !function utils.textcaps_rougel
    higher_is_better : true
  - metric: textcaps_CIDEr
    aggregation : !function utils.textcaps_cider
    higher_is_better : true
  - metric: textcaps_POLOS
    aggregation : !function utils.textcaps_polos
    higher_is_better : true
