dataset_path: json
dataset_kwargs:
  data_files:
    test: hf://datasets/xiang709/VRSBench/VRSBench_EVAL_vqa.json
task: vrsbench_vqa
test_split: test
output_type: generate_until
doc_to_visual: !function utils.vrsbench_doc_to_visual
doc_to_text: !function utils.vrsbench_vqa_doc_to_text
doc_to_target: !function utils.vrsbench_vqa_doc_to_target
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.vrsbench_vqa_process_results
metric_list:
  - metric: vqa_accuracy
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_existence
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_quantity
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_color
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_position
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_category
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_scene_type
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_shape
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_size
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_reasoning
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_object_direction
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_rural_or_urban
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
  - metric: vqa_image
    aggregation: !function utils.vrsbench_vqa_aggregate
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
metadata:
  - version: 0.0
